dataset:
  name: imagenet
  root: ~/datasets/ILSVRC2012
  train:
    split: train
    make_partial: 0.1
  val:
    split: val
  resize: 224

training:
  optimizer:
    name: AdamW
    lr: 1.0e-3
    weight_decay: 0.05
  lr_schedule:
    name: cosine_annealing
    T_max: 240
  train_epochs: 240
  print_interval: 20
  val_interval: 1000
  batch_size: 64
  num_workers: 16
  sync_bn: True

validation:
  batch_size: 64
  num_workers: 16

model:
  # cfg names
  name: cnn
  cnn_name: cnn_block
  input_proj:
    name: resnet_like
    image_channels: 3
    activation: gelu
    mid_channel: 64
  conv_block:
    name: conv_manyhead
    bias: True
    num_heads: 6
  mlp_block:
    name: mlp_cnn
    dim_feedforward: 1536
    dropout: 0.1
  down_sample_layers: [2, 8]
  # transformers info
  embed_dim: 384
  num_layers: 12
  # others
  norm:
    name: bn
  activation: gelu
  pre_norm: False

loss:
  name: ce_loss
  weight_dict:
    cls: 1.0
